package com.model.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QueryWalletBasicDataExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public QueryWalletBasicDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_wallet_basic_data
     *
     * @mbggenerated Fri Apr 21 10:56:14 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andStatDateIsNull() {
            addCriterion("stat_date is null");
            return (Criteria) this;
        }

        public Criteria andStatDateIsNotNull() {
            addCriterion("stat_date is not null");
            return (Criteria) this;
        }

        public Criteria andStatDateEqualTo(Date value) {
            addCriterionForJDBCDate("stat_date =", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("stat_date <>", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateGreaterThan(Date value) {
            addCriterionForJDBCDate("stat_date >", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stat_date >=", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateLessThan(Date value) {
            addCriterionForJDBCDate("stat_date <", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stat_date <=", value, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateIn(List<Date> values) {
            addCriterionForJDBCDate("stat_date in", values, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("stat_date not in", values, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stat_date between", value1, value2, "statDate");
            return (Criteria) this;
        }

        public Criteria andStatDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stat_date not between", value1, value2, "statDate");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayIsNull() {
            addCriterion("wallet_purchase_amount_day is null");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayIsNotNull() {
            addCriterion("wallet_purchase_amount_day is not null");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayEqualTo(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day =", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayNotEqualTo(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day <>", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayGreaterThan(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day >", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day >=", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayLessThan(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day <", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wallet_purchase_amount_day <=", value, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayIn(List<BigDecimal> values) {
            addCriterion("wallet_purchase_amount_day in", values, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayNotIn(List<BigDecimal> values) {
            addCriterion("wallet_purchase_amount_day not in", values, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wallet_purchase_amount_day between", value1, value2, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andWalletPurchaseAmountDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wallet_purchase_amount_day not between", value1, value2, "walletPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayIsNull() {
            addCriterion("redem_debpt_purchase_amount_day is null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayIsNotNull() {
            addCriterion("redem_debpt_purchase_amount_day is not null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day =", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayNotEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day <>", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayGreaterThan(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day >", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day >=", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayLessThan(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day <", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_purchase_amount_day <=", value, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_purchase_amount_day in", values, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayNotIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_purchase_amount_day not in", values, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_purchase_amount_day between", value1, value2, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptPurchaseAmountDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_purchase_amount_day not between", value1, value2, "redemDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayIsNull() {
            addCriterion("base_debpt_purchase_amount_day is null");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayIsNotNull() {
            addCriterion("base_debpt_purchase_amount_day is not null");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day =", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayNotEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day <>", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayGreaterThan(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day >", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day >=", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayLessThan(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day <", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_day <=", value, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayIn(List<BigDecimal> values) {
            addCriterion("base_debpt_purchase_amount_day in", values, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayNotIn(List<BigDecimal> values) {
            addCriterion("base_debpt_purchase_amount_day not in", values, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_debpt_purchase_amount_day between", value1, value2, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_debpt_purchase_amount_day not between", value1, value2, "baseDebptPurchaseAmountDay");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlIsNull() {
            addCriterion("base_debpt_purchase_amount_ttl is null");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlIsNotNull() {
            addCriterion("base_debpt_purchase_amount_ttl is not null");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl =", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlNotEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl <>", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlGreaterThan(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl >", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl >=", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlLessThan(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl <", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("base_debpt_purchase_amount_ttl <=", value, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlIn(List<BigDecimal> values) {
            addCriterion("base_debpt_purchase_amount_ttl in", values, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlNotIn(List<BigDecimal> values) {
            addCriterion("base_debpt_purchase_amount_ttl not in", values, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_debpt_purchase_amount_ttl between", value1, value2, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andBaseDebptPurchaseAmountTtlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_debpt_purchase_amount_ttl not between", value1, value2, "baseDebptPurchaseAmountTtl");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayIsNull() {
            addCriterion("redem_debpt_apply_amount_day is null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayIsNotNull() {
            addCriterion("redem_debpt_apply_amount_day is not null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day =", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayNotEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day <>", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayGreaterThan(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day >", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day >=", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayLessThan(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day <", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_amount_day <=", value, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_apply_amount_day in", values, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayNotIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_apply_amount_day not in", values, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_apply_amount_day between", value1, value2, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyAmountDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_apply_amount_day not between", value1, value2, "redemDebptApplyAmountDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayIsNull() {
            addCriterion("redem_debpt_apply_balance_day is null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayIsNotNull() {
            addCriterion("redem_debpt_apply_balance_day is not null");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day =", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayNotEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day <>", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayGreaterThan(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day >", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day >=", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayLessThan(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day <", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("redem_debpt_apply_balance_day <=", value, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_apply_balance_day in", values, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayNotIn(List<BigDecimal> values) {
            addCriterion("redem_debpt_apply_balance_day not in", values, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_apply_balance_day between", value1, value2, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andRedemDebptApplyBalanceDayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("redem_debpt_apply_balance_day not between", value1, value2, "redemDebptApplyBalanceDay");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayIsNull() {
            addCriterion("borrower_repayment_today is null");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayIsNotNull() {
            addCriterion("borrower_repayment_today is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_today =", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayNotEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_today <>", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayGreaterThan(BigDecimal value) {
            addCriterion("borrower_repayment_today >", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_today >=", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayLessThan(BigDecimal value) {
            addCriterion("borrower_repayment_today <", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_today <=", value, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayIn(List<BigDecimal> values) {
            addCriterion("borrower_repayment_today in", values, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayNotIn(List<BigDecimal> values) {
            addCriterion("borrower_repayment_today not in", values, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("borrower_repayment_today between", value1, value2, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTodayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("borrower_repayment_today not between", value1, value2, "borrowerRepaymentToday");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalIsNull() {
            addCriterion("borrower_repayment_total is null");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalIsNotNull() {
            addCriterion("borrower_repayment_total is not null");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_total =", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalNotEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_total <>", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalGreaterThan(BigDecimal value) {
            addCriterion("borrower_repayment_total >", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_total >=", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalLessThan(BigDecimal value) {
            addCriterion("borrower_repayment_total <", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("borrower_repayment_total <=", value, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalIn(List<BigDecimal> values) {
            addCriterion("borrower_repayment_total in", values, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalNotIn(List<BigDecimal> values) {
            addCriterion("borrower_repayment_total not in", values, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("borrower_repayment_total between", value1, value2, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andBorrowerRepaymentTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("borrower_repayment_total not between", value1, value2, "borrowerRepaymentTotal");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletIsNull() {
            addCriterion("pay_interest_wallet is null");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletIsNotNull() {
            addCriterion("pay_interest_wallet is not null");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletEqualTo(BigDecimal value) {
            addCriterion("pay_interest_wallet =", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletNotEqualTo(BigDecimal value) {
            addCriterion("pay_interest_wallet <>", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletGreaterThan(BigDecimal value) {
            addCriterion("pay_interest_wallet >", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_interest_wallet >=", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletLessThan(BigDecimal value) {
            addCriterion("pay_interest_wallet <", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_interest_wallet <=", value, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletIn(List<BigDecimal> values) {
            addCriterion("pay_interest_wallet in", values, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletNotIn(List<BigDecimal> values) {
            addCriterion("pay_interest_wallet not in", values, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_interest_wallet between", value1, value2, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andPayInterestWalletNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_interest_wallet not between", value1, value2, "payInterestWallet");
            return (Criteria) this;
        }

        public Criteria andWalletStockIsNull() {
            addCriterion("wallet_stock is null");
            return (Criteria) this;
        }

        public Criteria andWalletStockIsNotNull() {
            addCriterion("wallet_stock is not null");
            return (Criteria) this;
        }

        public Criteria andWalletStockEqualTo(BigDecimal value) {
            addCriterion("wallet_stock =", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockNotEqualTo(BigDecimal value) {
            addCriterion("wallet_stock <>", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockGreaterThan(BigDecimal value) {
            addCriterion("wallet_stock >", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wallet_stock >=", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockLessThan(BigDecimal value) {
            addCriterion("wallet_stock <", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wallet_stock <=", value, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockIn(List<BigDecimal> values) {
            addCriterion("wallet_stock in", values, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockNotIn(List<BigDecimal> values) {
            addCriterion("wallet_stock not in", values, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wallet_stock between", value1, value2, "walletStock");
            return (Criteria) this;
        }

        public Criteria andWalletStockNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wallet_stock not between", value1, value2, "walletStock");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletIsNull() {
            addCriterion("deal_interest_wallet is null");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletIsNotNull() {
            addCriterion("deal_interest_wallet is not null");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletEqualTo(BigDecimal value) {
            addCriterion("deal_interest_wallet =", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletNotEqualTo(BigDecimal value) {
            addCriterion("deal_interest_wallet <>", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletGreaterThan(BigDecimal value) {
            addCriterion("deal_interest_wallet >", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deal_interest_wallet >=", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletLessThan(BigDecimal value) {
            addCriterion("deal_interest_wallet <", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deal_interest_wallet <=", value, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletIn(List<BigDecimal> values) {
            addCriterion("deal_interest_wallet in", values, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletNotIn(List<BigDecimal> values) {
            addCriterion("deal_interest_wallet not in", values, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deal_interest_wallet between", value1, value2, "dealInterestWallet");
            return (Criteria) this;
        }

        public Criteria andDealInterestWalletNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deal_interest_wallet not between", value1, value2, "dealInterestWallet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_wallet_basic_data
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 21 10:56:14 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_wallet_basic_data
     *
     * @mbggenerated Fri Apr 21 10:56:14 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}